### ISSUE TITLE
Error in exec

### ISSUE THREAD

**Issue by stefanwalther** [gokhansengun/Docker-Hub-Flyway-Postgres#1]
Hi,

I get the following error:

```
oci runtime error: exec: "curl": executable file not found in $PATH
```

**Comment by gokhansengun** [comment]
Hi Stefan,

I think you followed the doc (README) which was using version 1.1 and misleading, fixed that now. Please let me know if this fixes the issue for you. If not, please tell me the steps you followed to reproduce the issue.

Thanks.
